## UniFlex Agent config file

config:
  name: 'HC node'
  info: 'filter runs on local node'
  iface: 'lo'

control_applications:
  myFilter:
      file : my_filter.py
      class_name : MyAvgFilter
      kwargs : {"window": 5}

  discovery:
      module : uniflex_app_discovery_pyre
      class_name : PyreDiscoverySlaveModule
      kwargs: {"iface":"lo", "groupName":"uniflex_1234"}

modules:
  simple:
      module : uniflex_module_simple
      class_name : SimpleModule4
      devices : ['phy0']
      kwargs : { "clients" : ["cc:cc:cc:cc:cc:01"], 
        'neighbors' : ['aa:aa:aa:aa:aa:02', 'aa:aa:aa:aa:aa:03'],
        'myMAC' : 'aa:aa:aa:aa:aa:01',
        'simulation': {'channelSwitchingTime': 200, 'channelThroughput':54000000, 'txBytesRandom':0.2}}

